emh_membres_inscription:
    pattern: /inscription/formation/{id}
    defaults: { _controller: "emhMembresBundle:Membre:add" }

emh_membres_profil:
    pattern:  /membre/profile
    defaults: { _controller: "emhMembresBundle:Membre:test" }
