services:
    sonata.admin.Membres:
        class: emh\MembresBundle\Admin\MembreAdmin
                
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Membres" }
         
        arguments:
            - ~
            - emh\MembresBundle\Entity\Membres
          
            - ~
        calls:
            - [ setTranslationDomain, [emhMembres]]
            
   
            

