parameters:
#    emh_membres.example.class: emh\MembresBundle\Example

services:
#    emh_membres.example:
#        class: %emh_membres.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
