security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/emh/secured/login$
            security: false

        secured_area:
            pattern:    ^/emh/secured/
            form_login:
                check_path: _security_check
                always_use_default_target_path : true
                default_target_path: /emh/rubrique
               
            
        main:
            pattern:        ^/
            anonymous:      true
            provider:       fos_userbundle
            
            form_login:
                login_path: fos_user_security_login 
                check_path: fos_user_security_check

            logout:
                path:       /logout
                target:     /accueil
            
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml
            
            
            anonymous:    true
                
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
         # Liste des pages accessibles à tous les utilisateurs (ne pas toucher)
        - { path: ^/_wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resseting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # PAGES ACCESSIBLES AUX ADMINISTRATEURS
        - { path: ^/emh/admin/, role: ROLE_ADMIN }
        - { path: ^/emh/formation/admin/, role: ROLE_ADMIN }
        - { path: ^/emh/membre/admin/, role: ROLE_ADMIN }
        
        # PAGES ACCESSIBLES AUX UTILISATEURS CONNECTES
        - { path: ^/emh/change-password, role: ROLE_USER }

        # PAGES ACCESSIBLES À TOUS
        - { path: ^/emh.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

# FOS user configuration

       

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/formation/admin/, role: ROLE_ADMIN }
        - { path: ^/membre/admin/, role: ROLE_ADMIN }
        
