emh_formation:
    pattern:  /
    defaults: { _controller: emhInscriptionBundle:Formation:liste }

emh_formation_detail:
    pattern:  /formation/{id}/detail
    defaults: { _controller: emhInscriptionBundle:Formation:detail  }



emh_membres_formation_paypal:
    pattern: /{id}/paypal/confirmation
    defaults: { _controller: "emhInscriptionBundle:Inscription:paypal" }
    
emh_membres_confirmation:
    pattern: /confirmation/do/{id}
    defaults: { _controller: "emhInscriptionBundle:Inscription:process" }

