emh_formation:
    pattern:  /
    defaults: { _controller: emhInscriptionBundle:Formation:liste }
# A utiliser dans le path du lien      
emh_formation_detail:
    pattern:  /formation/{id}/detail
    defaults: { _controller: emhInscriptionBundle:Formation:detail  }

emh_formation_edit:
    pattern:  /admin/formation/{id}/edit
    defaults: { _controller: emhInscriptionBundle:Formation:edit }

emh_formation_delete:
    pattern:  /admin/formation/{id}/delete
    defaults: { _controller: emhInscriptionBundle:Formation:delete}

emh_formation_add:
    pattern:  /admin/formation/add
    defaults: { _controller: emhInscriptionBundle:Formation:add }  
