emh_formation:
    pattern:  /
    defaults: { _controller: emhInscriptionBundle:Formation:liste }

emh_formation_detail:
    pattern:  /formation/{id}/detail
    defaults: { _controller: emhInscriptionBundle:Formation:detail  }



emh_membres_inscription:
    pattern: /inscription/formation/{id}
    defaults: { _controller: "emhInscriptionBundle:Inscription:add" }
    
emh_membres_desinscription:
    pattern:  /desinscription/formation/{id}
    defaults: { _controller: "emhInscriptionBundle:Inscription::delete" }

