services:
    sonata.admin.Formation:
        class: emh\InscriptionBundle\Admin\FormationsAteliersAdmin
                
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Formations", label: "Formations" }
         
        arguments:
            - ~
            - emh\InscriptionBundle\Entity\FormationsAteliers
          
            - ~
        calls:
            - [ setTranslationDomain, [InscriptionBundle]]
            
    sonata.admin.Inscriptions:
        class: emh\InscriptionBundle\Admin\InscriptionsAdmin
                
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Formations", label: "Inscriptions" }
         
        arguments:
            - ~
            - emh\InscriptionBundle\Entity\Inscriptions
          
            - ~
        calls:
            - [ setTranslationDomain, [InscriptionBundle]]
            
   
            

