parameters:
#    emh_inscription.example.class: emh\InscriptionBundle\Example

services:
#    emh_inscription.example:
#        class: %emh_inscription.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
