services:
    sonata.admin.Inscription:
        class: emh\InscriptionBundle\Admin\InscriptionAdmin
                
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Formations" }
         
        arguments:
            - ~
            - emh\InscriptionBundle\Entity\FormationsAteliers
          
            - ~
        calls:
            - [ setTranslationDomain, [emhInscription]]
            
   
            

