cms_principal_contact:
    pattern: /contact
    defaults : {_controller: emhcmsPrincipalBundle:Contact:index }
    
cms_principal_page:
    pattern:  /{slugFr}
    defaults: { _controller: emhcmsPrincipalBundle:Rubrique:detail }
    
cms_principal_article:
    pattern:  /{id}/{slugFr}/detail
    defaults: { _controller: emhcmsPrincipalBundle:Article:detail }
    

