cms_principal_page:
    pattern:  /{slug}
    defaults: { _controller: emhcmsPrincipalBundle:Rubrique:detail }
    
cms_principal_rubrique_edit:
    pattern:  /admin/rubrique/{id}/edit
    defaults: { _controller: emhcmsPrincipalBundle:Rubrique:edit } 
    
cms_principal_rubrique_add:
    pattern: /admin/rubrique/add
    defaults: { _controller: emhcmsPrincipalBundle:Rubrique:add }  
    
cms_principal_article_add:
    pattern:  /admin/article/add
    defaults: { _controller: emhcmsPrincipalBundle:Article:add }    
  
    
cms_principal_rubrique_delete:
    pattern:  /admin/rubrique/{id}/delete
    defaults: { _controller: emhcmsPrincipalBundle:Rubrique:delete}


    
cms_principal_article_edit:
    pattern:  /admin/article/{id}/edit
    defaults: { _controller: emhcmsPrincipalBundle:Article:edit }

cms_principal_article_delete:
    pattern:  /admin/article/{id}/delete
    defaults: { _controller: emhcmsPrincipalBundle:Article:delete}