services:
    sonata.admin.Rubrique:
        class: emh\cmsPrincipalBundle\Admin\PostAdmin
                
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Menu", label: "Rubriques" }
         
        arguments:
            - ~
            - emh\cmsPrincipalBundle\Entity\Rubriques
          
            - ~
        calls:
            - [ setTranslationDomain, [emhcmsPrincipal]]
            
    sonata.admin.Article:
        class: emh\cmsPrincipalBundle\Admin\PostArticleAdmin
                
        tags:
           
            - { name: sonata.admin, manager_type: orm, group: "Contenu", label: "Articles" }
        arguments:
            - ~
          
            - emh\cmsPrincipalBundle\Entity\Articles
            - ~
        calls:
            - [ setTranslationDomain, [emhcmsPrincipal]]

    emh.form.articles:
        class: emh\cmsPrincipalBundle\Form\ArticlesType
        tags:
            - { name: form.type, alias: articles }
            
            
            

