parameters:
#    emhcms_principal.example.class: emh\cmsPrincipalBundle\Example

services:
#    emhcms_principal.example:
#        class: %emhcms_principal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    
