
emh_membres_produit_paypal:
    pattern: /{id}/paypal/confirmation
    defaults: { _controller: "emhEcommerceBundle:Achat:paypal" }
    
emh_membres_confirmation_achat:
    pattern: /confirmation/do/{id}
    defaults: { _controller: "emhEcommerceBundle:Achat:process" }


emh_ecommerce_liste_produits:
    pattern:  /
    defaults: { _controller: emhEcommerceBundle:Produit:liste }

emh_ecommerce_detail_produit:
    pattern:  /produit/{id}/detail
    defaults: { _controller: emhEcommerceBundle:Produit:detail }

    