parameters:
#    emh_ecommerce.example.class: emh\EcommerceBundle\Example

services:
#    emh_ecommerce.example:
#        class: %emh_ecommerce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
